ciq_data = {
    "KUL": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "A/C Security Checklist prepared by crew(TAA Ver.)",
        "gdoc_required": "Required",
        "pax_manifest": "6 copies (DMK-KUL) prepared by GS",
        "special_announcement": "Drug & Human trafficking Malaysia Digital Arrival Cards and Autogates (Live)",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "60 MYR",
        "utc_offset": "+0800",
        "remark": "6 copies (KUL-DMK) prepared by GS"
    },
    "PEN": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "Required",
        "gdoc_required": "2 copies prepared by GS",
        "pax_manifest": "N",
        "special_announcement": "N",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "60 MYR",
        "utc_offset": "+0800",
        "remark": ""
    },
    "JHB": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "Required",
        "gdoc_required": "2 copies prepared by GS",
        "pax_manifest": "N",
        "special_announcement": "N",
        "headcount": "Y",
        "step_down_immigration": "N",
        "wchr": "60 MYR",
        "utc_offset": "+0800",
        "remark": "-P4 collects all crew pasports before door closing at DMK for immigration clearance at JHB\n-P4 brings GD(DMK-JHB) with all crew passports for immigration clearance at JHB"
    },
    "SIN": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "A/C Security Checklist prepared by crew (TAA Ver.) A/C Security Checklist prepared by GS/SIN(CAAS Version)",
        "gdoc_required": "Not required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "Drug trafficking & Weapon carrying Automated Clearance",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "20 SGD",
        "utc_offset": "+0800",
        "remark": "All rubbish bags must be brought back to DMK by keeping in the cabin"
    },
    "HKG": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "A/C Security Checklist prepared by crew (TAA Ver.)",
        "gdoc_required": "Required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "Smoking(Public Health) Monkeypox Beware of belongings",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "Free",
        "utc_offset": "+0800",
        "remark": ""
    },
    "RGN": {
        "immigration_form": "Y",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "A/C Security Checklist prepared by crew (TAA Ver.)",
        "gdoc_required": "Not required",
        "pax_manifest": "4 copies prepared by GS",
        "special_announcement": "",
        "headcount": "Y",
        "step_down_immigration": "N",
        "wchr": "20 USD",
        "utc_offset": "+0630",
        "remark": "-After all inbound pax passed imm. clearance process/ wait for permission from staff then A/C door can be close & depart\n-All operating crews of all flights entering Myanmar must wear the face mask throughout the flight"
    },
    "MDL": {
        "immigration_form": "Y",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "",
        "gdoc_required": "Not required",
        "pax_manifest": "4 copies prepared by GS",
        "special_announcement": "",
        "headcount": "Y",
        "step_down_immigration": "N",
        "wchr": "20 USD",
        "utc_offset": "+0630",
        "remark": "All operating crews of all flights entering Myanmar must wear the face mask throughout the flight"
    },
    "LPQ": {
        "immigration_form": "Y",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "A/C Security Checklist prepared by crew (TAA Ver.)",
        "gdoc_required": "Not required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "Human Trafficking CUSTOMS and Bank of Lao PDR",
        "headcount": "Y",
        "step_down_immigration": "N",
        "wchr": "20 USD",
        "utc_offset": "+0700",
        "remark": "10 countries no need VOA - Thai, Sin, Vietnam, Malay, Brunei, Myanmar, Indo, Philiphine, Cambodia & Lao. (4 countries of exemption; stay 15 days -Japan, South Korea, Russia, and Swistzerland)"
    },
    "VTE": {
        "immigration_form": "Y",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "",
        "gdoc_required": "Not required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "",
        "headcount": "Y",
        "step_down_immigration": "N",
        "wchr": "20 USD",
        "utc_offset": "+0700",
        "remark": ""
    },
    "SGN": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "A/C Security Checklist prepared by crew (TAA Ver.)",
        "gdoc_required": "Not required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "Customs(FAP) Beware of belongings",
        "headcount": "Y",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0700",
        "remark": ""
    },
    "CXR": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "",
        "gdoc_required": "Not required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "",
        "headcount": "Y",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0700",
        "remark": ""
    },
    "DAD": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "",
        "gdoc_required": "Not required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "",
        "headcount": "Y",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0700",
        "remark": "Should there be garbage bags to dispose, SCC shall signs garbage bag handover form.(refer to email)"
    },
    "HAN": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "",
        "gdoc_required": "Not required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "",
        "headcount": "Y",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0700",
        "remark": ""
    },
    "PQC": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "",
        "gdoc_required": "Not required",
        "pax_manifest": "5 copies prepared by GS",
        "special_announcement": "",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0700",
        "remark": ""
    },
    "PNH": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "",
        "gdoc_required": "Not required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "Beware of belongings",
        "headcount": "Y",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0700",
        "remark": ""
    },
    "SAI": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "",
        "gdoc_required": "Not required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "",
        "headcount": "Y",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0700",
        "remark": "All rubbish bags must be brought back to DMK by handing it over to GHA to keep in cargo hold."
    },
    "MLE": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "",
        "gdoc_required": "Required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "MLE special announcement",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0500",
        "remark": ""
    },
    "DPS": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "",
        "gdoc_required": "Not required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "No Smoking in Terminal Currency Declaration For Indonesia Routes MPox",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0800",
        "remark": ""
    },
    "CGK": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "",
        "gdoc_required": "Not required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "No Smoking in Terminal Currency Declaration For Indonesia Routes MPox",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0700",
        "remark": ""
    },
    "TRZ": {
        "immigration_form": "Y",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "1.A/C Security Checklist prepared by crew (TAA Ver.) 2.A/C Security Checklist prepared by India GS(India Ver.)",
        "gdoc_required": "Required",
        "pax_manifest": "3 copies prepared by GS",
        "special_announcement": "India CIQ Announcement",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0530",
        "remark": "Pre-embarkation (pre-flight) disinsection process\n-An extra GD printed by cabin crew\n- Once cabin crews board the A/C, SCC is to ensure an empty spray can is placed at FWD galley.( In case it is unavailable, notify the engineer immediately)\n- SCC keeps an empty spray can in the proper area away from food.\n - After door opening at TRZ, SCC hands an empty spray can and extra GD together with all onboard documents to GS."
    },
    "CCU": {
        "immigration_form": "Y",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "1.Baggage Declaration form\n2.Temporary Crew Landing Permit Form 3.A/C Security Checklist prepared by crew (TAA Ver.) 4.A/C Security Checklist prepared by India GS(India Ver.)",
        "gdoc_required": "Required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "India CIQ Announcement",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0530",
        "remark": ""
    },
    "GAY": {
        "immigration_form": "Y",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "1.A/C Security Checklist prepared by crew (TAA Ver.) 2.A/C Security Checklist prepared by India GS(India Ver.)",
        "gdoc_required": "Required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "India CIQ Announcement",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0530",
        "remark": ""
    },
    "AMD": {
        "immigration_form": "Y",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "1.A/C Security Checklist prepared by crew (TAA Ver.) 2.A/C Security Checklist prepared by India GS(India Ver.)",
        "gdoc_required": "Required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "India CIQ Announcement",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0530",
        "remark": ""
    },
    "JAI": {
        "immigration_form": "Y",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "1.A/C Security Checklist prepared by crew (TAA Ver.) 2.A/C Security Checklist prepared by India GS(India Ver.)",
        "gdoc_required": "Required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "India CIQ Announcement",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0530",
        "remark": ""
    },
    "MAA": {
        "immigration_form": "Y",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "1.Baggage Declaration form\n2.Temporary Crew Landing Permit Form 3.A/C Security Checklist prepared crew (TAA Ver.) 4.A/C Security Checklist prepared by India GS(India Ver.)",
        "gdoc_required": "Required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "India CIQ Announcement",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0530",
        "remark": ""
    },
    "BLR": {
        "immigration_form": "Y",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "1.A/C Security Checklist prepared by crew (TAA Ver.) 2.A/C Security Checklist prepared by India GS(India Ver.)",
        "gdoc_required": "Required",
        "pax_manifest": "3 copies prepared by GS",
        "special_announcement": "India CIQ Announcement",
        "headcount": "Y",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0530",
        "remark": ""
    },
    "COK": {
        "immigration_form": "Y",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "1.A/C Security Checklist prepared by crew (TAA Ver.) 2.A/C Security Checklist prepared by India GS(India Ver.)",
        "gdoc_required": "Required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "India CIQ Announcement",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0530",
        "remark": "Pre-embarkation (pre-flight) disinsection process\n- Once cabin crews board the aircraft, SCC is to ensure an empty spray can is placed at the FWD galley.( In case it is unavailable, notify the engineer immediately)\n- SCC keeps an empty spray can in the proper area away from food.\n - After door opening at COK, SCC hands an empty spray can together with all onboard documents to GS."
    },
    "GAU": {
        "immigration_form": "Y",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "1.A/C Security Checklist prepared by crew (TAA Ver.) 2.A/C Security Checklist prepared by India GS(India Ver.)",
        "gdoc_required": "Required",
        "pax_manifest": "3 copies prepared by GS",
        "special_announcement": "India CIQ Announcement",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0530",
        "remark": "All rubbish bags must be brought back to DMK by keeping in the cabin"
    },
    "LKO": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "1.A/C Security Checklist prepared by crew (TAA Ver.) 2.A/C Security Checklist prepared by India GS(India Ver.)",
        "gdoc_required": "Required",
        "pax_manifest": "3 copies prepared by GS",
        "special_announcement": "India CIQ Announcement",
        "headcount": "Y",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0530",
        "remark": ""
    },
    "VTZ": {
        "immigration_form": "Y",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "1.A/C Security Checklist prepared by crew (TAA Ver.) 2.A/C Security Checklist prepared by India GS(India Ver.)",
        "gdoc_required": "Required",
        "pax_manifest": "5 copies prepared by GS",
        "special_announcement": "VTZ special announcement\nIndia CIQ Announcement",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0530",
        "remark": "Immigration forms will be distributed to foreign nationals only"
    },
    "HYD": {
        "immigration_form": "Y",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "1.A/C Security Checklist prepared by crew (TAA Ver.) 2.A/C Security Checklist prepared by India GS(India Ver.)",
        "gdoc_required": "Required",
        "pax_manifest": "4 copies prepared by GS",
        "special_announcement": "India CIQ Announcement",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0530",
        "remark": "Immigration forms will be distributed to foreign nationals only"
    },
    "DAC": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "A/C Security Checklist prepared by crew (TAA Ver.)",
        "gdoc_required": "Not required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0600",
        "remark": ""
    },
    "FUK": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "A/C Security Checklist prepared by crew (TAA Ver.)",
        "gdoc_required": "Not required",
        "pax_manifest": "6 copies prepared by GS",
        "special_announcement": "Prohibition on Bringing Food on Board to Japan (Live) Visit Japan Web (Live) Quarantine (FAP)",
        "headcount": "N",
        "step_down_immigration": "Y",
        "wchr": "FREE",
        "utc_offset": "+0900",
        "remark": "All rubbish bags must be brought back to DMK by handing it over to GS to keep in cargo hold."
    },
    "OKA": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "A/C Security Checklist prepared by crew (TAA Ver.)",
        "gdoc_required": "Not required",
        "pax_manifest": "6 copies prepared by GS",
        "special_announcement": "",
        "headcount": "N",
        "step_down_immigration": "Y",
        "wchr": "FREE",
        "utc_offset": "+0900",
        "remark": "All rubbish bags must be brought back to DMK by handing it over to GHA to keep in cargo hold.\n-FD240/241 (quick turn),No step down for Immigration Clearance."
    },
    "NRT": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "A/C Security Checklist prepared by crew (TAA Ver.)",
        "gdoc_required": "Not required",
        "pax_manifest": "6 copies prepared by GS",
        "special_announcement": "",
        "headcount": "Y",
        "step_down_immigration": "FREE",
        "wchr": "FREE",
        "utc_offset": "+0900",
        "remark": "All rubbish bags must be brought back to DMK by handing it over to GHA to keep in cargo hold."
    },
    "TPE": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "A/C Security Checklist prepared by crew (TAA Ver.)",
        "gdoc_required": "Not required",
        "pax_manifest": "2 copies prpared by GS",
        "special_announcement": "Taiwan African Fever",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0800",
        "remark": ""
    },
    "KHH": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "A/C Security Checklist prepared by crew (TAA Ver.)",
        "gdoc_required": "Not required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0800",
        "remark": ""
    },
    "MFM": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "A/C Security Checklist prepared by crew (TAA Ver.)",
        "gdoc_required": "Required",
        "pax_manifest": "2 copies prepared by GS",
        "special_announcement": "Dengue Fever Beware of belongings",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0800",
        "remark": ""
    },
    "CMB": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "1.A/C Security Checklist prepared by crew (TAA Ver.) 2.2 copies of Colombo Custom Form printed by crew (in Redcrew)",
        "gdoc_required": "Required",
        "pax_manifest": "3 copies prepared by GS",
        "special_announcement": "",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0530",
        "remark": "SCC needs to print out 2 copies of Colombo Custom Form and complete them with all crew member signature. Airasia stamp is provided at Flight Operations."
    },
    "KTM": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "A/C Security Checklist prepared by crew (TAA Ver.)",
        "gdoc_required": "Not required",
        "pax_manifest": "6 copies prepared by GS",
        "special_announcement": "",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0545",
        "remark": ""
    },
    "BWA": {
        "immigration_form": "N",
        "customs_form": "N",
        "health_declaration": "N",
        "special_document": "A/C Security Checklist prepared by crew (TAA Ver.)",
        "gdoc_required": "Not required",
        "pax_manifest": "6 copies prepared by GS",
        "special_announcement": "",
        "headcount": "N",
        "step_down_immigration": "N",
        "wchr": "FREE",
        "utc_offset": "+0545",
        "remark": ""
    }
}